name: search

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - hydra-core
  - pandas
  - tqdm
  pip:
    - arxiv
    - biopython
    - python-dotenv
    - ipython
    - openai